from starkcore.utils.resource import Resource
from starkcore.utils.checks import check_date, check_datetime
from ..utils import rest


class IssuingStock(Resource):
    """# IssuingStock object
    The IssuingStock object displays the current stock of the workspace,
    which is the result of the sum of all transactions within this
    workspace. The balance is never generated by the user, but it
    can be retrieved to see the available information.
    ## Attributes (return-only):
    - id [string]: unique id returned when IssuingStock is created. ex: "5656565656565656"
    - design_id [string]: Issuer design id. ex: "5656565656565656"
    - embosser_id [string]: Embosser id. ex: "5656565656565656"
    - sub_issuer_id [string]: SubIssuer id. ex: "5656565656565656"
    - tags [string]: [list of strings, default []]: list of strings for reference when searching for PixReversals. ex: ["employees", "monthly"]
    - updated [datetime.datetime]: latest update datetime for the IssuingStock. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    - created [datetime.datetime]: creation datetime for the IssuingStock. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    """

    def __init__(self, design_id, embosser_id, sub_issuer_id, tags, id=None, created=None, updated=None):
        Resource.__init__(self, id=id)

        self.design_id = design_id
        self.embosser_id = embosser_id
        self.sub_issuer_id = sub_issuer_id
        self.tags = tags
        self.created = check_datetime(created)
        self.updated = check_datetime(updated)


_resource = {"class": IssuingStock, "name": "IssuingStock"}


def query(
    limit=None, after=None, before=None, status=None, design_ids=None, 
    embosser_ids=None, ids=None, tags=None, expand=None, user=None
):
    """# Retrieve IssuingStocks
    Receive a generator of IssuingStock objects previously created in the Stark Infra API
    ## Parameters (optional):
    - limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
    - after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
    - status [list of strings, default None]: filter for status of retrieved objects. ex: ["active", "blocked", "canceled", "expired"]
    - design_ids [list of strings, default None]: card type. ex: ["virtual"]
    - embosser_ids [list of strings]: card holder IDs. ex: ["5656565656565656", "4545454545454545"]
    - ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
    - tags [list of strings, default None]: tags to filter retrieved objects. ex: ["tony", "stark"]
    - expand [list of strings, default []]: fields to expand information. ex: ["balance"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - generator of IssuingStock objects with updated attributes
    """
    return rest.get_stream(
        resource=_resource,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        status=status,
        design_ids=design_ids,
        embosser_ids=embosser_ids,
        ids=ids,
        tags=tags,
        expand=expand,
        user=user,
    )


def page(
    cursor=None, limit=None, after=None, before=None, status=None, design_ids=None, 
    embosser_ids=None, ids=None, tags=None, expand=None, user=None
):
    """# Retrieve paged IssuingStocks
    Receive a list of IssuingStock objects previously created in the Stark Infra API and the cursor to the next page.
    ## Parameters (optional):
    - cursor [string, default None]: cursor returned on the previous page function call
    - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
    - after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
    - status [list of strings, default None]: filter for status of retrieved objects. ex: ["active", "blocked", "canceled", "expired"]
    - design_ids [list of strings, default None]: card type. ex: ["virtual"]
    - embosser_ids [list of strings]: card holder IDs. ex: ["5656565656565656", "4545454545454545"]
    - ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
    - tags [list of strings, default None]: tags to filter retrieved objects. ex: ["tony", "stark"]
    - expand [list of strings, default []]: fields to expand information. ex: ["balance"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - list of IssuingStock objects with updated attributes
    - cursor to retrieve the next page of IssuingStock objects
    """
    return rest.get_page(
        resource=_resource,
        cursor=cursor,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        status=status,
        design_ids=design_ids,
        embosser_ids=embosser_ids,
        ids=ids,
        tags=tags,
        expand=expand,
        user=user,
    )


def get(id, expand=None, user=None):
    """# Retrieve a specific IssuingStocks
    Receive a single IssuingStocks object previously created in the Stark Infra API by its id
    ## Parameters (required):
    - id [string]: object unique id. ex: "5656565656565656"
    ## Parameters (optional):
    - expand [list of strings, default None]: fields to expand information. ex: ["balance"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - IssuingStocks object with updated attributes
    """
    return rest.get_id(resource=_resource, id=id, expand=expand, user=user)
